### ISSUE TITLE
Command in Dockerfile returns non zero 

### ISSUE THREAD

**Issue by VNovotna** [hroncok/meshmixer-docker#3]
Command on line 4 in Dockerfile is returning non zero. This results in build fail. I can make it run by reordering of commands and adding true like this:
_dpkg -i /meshmixer.deb || apt-get update &&  apt-get install -y -f || true_

**Comment by hroncok** [comment]
And the install happens anyway?

**Comment by VNovotna** [comment]
It wrote this:

```
The command '/bin/sh -c dpkg -i /meshmixer.deb || apt-get update && apt-get install -y -f' returned a non-zero code: 100
Makefile:20: návod pro cíl „docker“ selhal
make: *** [docker] Chyba 1
```

and to be honest I didn't even tried to write `make run`.
But I'm almost sure no container was created, as docker didn't executed following steps from Dockefile.

**Comment by hroncok** [comment]
That's not what i mean, I mean if you add `|| true` to the command, if the installation of the packages works anyway?

**Comment by VNovotna** [comment]
If non-zero code is returned, Docker will terminate image creation. That's the problem.

**Comment by hroncok** [comment]
Yes. I see where the problem is. I'm talking about your proposed fix. `apt-get` ends with non-zero for a reason, if you add `|| true`, you are hiding that from Docker and make the build go on. The question here is, if it actually works (and `apt-get` ends with non-zero even when the installation was successful, because, well Ubuntu), or if the image builds successfully but incorrectly (when your fix is applied).

**Comment by VNovotna** [comment]
Well the meshmixer can be run, but it's complaining about "OpenGL Framebuffer Objects" and then the program look like this http://i.imgur.com/QIhP9HB.png . But I don't think it's related.

Because I installed Meshmixer on my Ubuntu 14.04 laptop (without docker) and the installation also returned non-zero code. And Meshmixer was working ok.

**Comment by hroncok** [comment]
OK than, will you send a pull request?
